spring.application.name=api
jwt.secret-key="404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
#jwt.secret-key=${JWT_SECRET_KEY}

spring.sql.init.mode=always
spring.sql.init.platform=postgres

# Database Configuration
#spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.jpa.properties..hibernate.default_schema=paw_project
#spring.datasource.url=jdbc:postgresql://foka.wi.local:5432/s51672
spring.datasource.url=jdbc:postgresql://localhost:5432/s51672
#spring.jpa.properties..hibernate.default_schema=${SPRING_DATASOURCE_SCHEMA}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.username=s51672
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.password=1Zb8Ru4Xq9Zb

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
